"""empty message

Revision ID: 69ffd75247d3
Revises: e6b33e32ede5
Create Date: 2021-03-27 10:14:52.470390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ffd75247d3'
down_revision = 'e6b33e32ede5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###
